### ISSUE TITLE
Update story extension

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/Awesome-Arcade-Extensions#16]
@riknoll rewrote the story extension and it will be in the list of built-in extensions. Meanwhile, the old one will become depreciated.

**Comment by riknoll** [comment]
The new one is here: https://github.com/microsoft/arcade-storytelling

**Comment by UnsignedArduino** [comment]
Ah thanks, sorry for pinging you didn't know that would actually ping

**Comment by riknoll** [comment]
hahaha no problem! Feel free to ping me on issues whenever.

**Comment by UnsignedArduino** [comment]
Forum post: https://forum.makecode.com/t/new-arcade-story-extension/6744
