### ISSUE TITLE
Add https://arcade-font-renderer.jacobcarpenter.com/

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/Awesome-Arcade-Extensions#19]
https://forum.makecode.com/t/arcade-font-renderer/7174

**Comment by jacobcarpenter** [comment]
I just came here to add this issue after happening to notice it wasn't in the list yet, but you beat me to it. 😅

**Comment by UnsignedArduino** [comment]
Haha yes sorry I've been pretty busy - I'll go put this in today
