### ISSUE TITLE
Add https://github.com/riknoll/arcade-platformer

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/Awesome-Arcade-Extensions#32]
**Link to GitHub repo**: https://github.com/riknoll/arcade-platformer
**Link to demo**: [Insert a GitHub pages link or an Arcade share link. Not required, but if included must demonstrate most features of the extension]
**Link to Forum post**: [Insert a link to a Forum post if the extension was introduced at forum.makecode.com. Not required]

**Comment by LucasMayhew** [comment]
I am sad that this has a bug

**Comment by UnsignedArduino** [comment]
I'm not sure if @riknoll ever finished this, so I put on `do not fix` so people don't try to add it and realize that it's "useless."

**Comment by LucasMayhew** [comment]
Oh okay

**Comment by UnsignedArduino** [comment]
I don't think @riknoll will finish this, so closing. (He said it was "not useful")

**Comment by LucasMayhew** [comment]
Still sad I can't easily switch gravity
