### ISSUE TITLE
Add https://github.com/livcheerful/arcade-soundtrack

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/Awesome-Arcade-Extensions#35]
**Link to GitHub repo**: https://github.com/livcheerful/arcade-soundtrack
**Link to demo**: [Insert a GitHub pages link or an Arcade share link. Not required, but if included must demonstrate most features of the extension]
**Link to Forum post**: [Insert a link to a Forum post if the extension was introduced at forum.makecode.com. Not required]

**Comment by UnsignedArduino** [comment]
Demo: https://makecode.com/_40EPWdWVi1LL
Forum post: https://forum.makecode.com/t/hackathon-link-request/9751/2?u=unsignedarduino

**Comment by LucasMayhew** [comment]
Hi @UnsignedArduino I added this to a forked project
https://github.com/LucasMayhew/Awesome-Arcade-Extensions#arcade-soundtrack

**Comment by UnsignedArduino** [comment]
@LucasMayhew ok then can you submit pr?

**Comment by UnsignedArduino** [comment]
I should probably get going on these anyways lol

**Comment by LucasMayhew** [comment]
Made Pull request
