### ISSUE TITLE
Add https://github.com/LucasMayhew/RPGMuisic

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/Awesome-Arcade-Extensions#40]
**Link to GitHub repo**: https://github.com/LucasMayhew/RPGMuisic
**Link to demo**: https://arcade.makecode.com/06547-32796-52098-57963
**Link to Forum post**: https://forum.makecode.com/t/an-extension-that-adds-loopable-songs-to-use-in-your-games/10894?u=unsignedarduino

**Comment by LucasMayhew** [comment]
Oh was about to ask you to add that
