### ISSUE TITLE
Add https://github.com/AqeeAqee/arcade-snapshot

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/Awesome-Arcade-Extensions#50]
**Link to GitHub repo**: https://github.com/AqeeAqee/arcade-snapshot
**Link to demo**: [Insert a GitHub pages link or an Arcade share link. Not required, but if included must demonstrate most features of the extension]
**Link to Forum post**: https://forum.makecode.com/t/a-snapshot-extension-for-screen-or-tilemap/13064

**Comment by AqeeAqee** [comment]
Wow, just found out you have adopt this in. Thanks for you like it!
Let me know please if need any support about it!
