### ISSUE TITLE
Update description of extension pxt-raycasting

### ISSUE THREAD

**Issue by AqeeAqee** [UnsignedArduino/Awesome-Arcade-Extensions#58]
Hi UnsignedArduino !
As the features like sayText and jump have been released, it's time to update introduction in your list. 
But for my poor english, cann't write out description even satisfied myself. So I just put off it again and again.
Would mind helping me write a new introduction of it and update it?

Thanks so much!

**Comment by AqeeAqee** [comment]
Hi @UnsignedArduino 
I forgot to ”at“ you in last post, maybe git would not notify you.
Sorry if you have been notified or you are busy on works. It's fine, feel free let me know, I will write it, even maybe not as good as yours.

**Comment by UnsignedArduino** [comment]
It's fine (I haven't checked my GitHub in a while)
I'll get to doing this soon, thanks 👍

**Comment by AqeeAqee** [comment]
Hi @UnsignedArduino 
It's not only updated, and moved into build-in extensions also.
Thank you so much!
