### ISSUE TITLE
Add https://github.com/riknoll/arcade-split-screen

### ISSUE THREAD

**Issue by UnsignedArduino** [UnsignedArduino/Awesome-Arcade-Extensions#66]
**Link to GitHub repo**: https://github.com/riknoll/arcade-split-screen
**Link to demo**: [Insert a GitHub pages link or an Arcade share link. Not required, but if included must demonstrate most features of the extension]
**Link to Forum post**: https://forum.makecode.com/t/extension-arcade-split-screen/14970?u=unsignedarduino

**Comment by S0m3randomguy** [comment]
Demo: https://arcade.makecode.com/66629-31960-05105-39180

**Comment by S0m3randomguy** [comment]
#67 Completed
