### ISSUE TITLE
Add https://github.com/meeeeeeeep1/custom-systemmenu-options/

### ISSUE THREAD

**Issue by Softalker101** [UnsignedArduino/Awesome-Arcade-Extensions#71]
https://github.com/meeeeeeeep1/custom-systemmenu-options/ 
yeah so a new one came

**Comment by UnsignedArduino** [comment]
Fixed by https://github.com/UnsignedArduino/Awesome-Arcade-Extensions-Website/commit/d5b9f8986ccaed2b559fd460063f818063c85810
